/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
 *
 * Generated on: 11-Feb-2014 09:41:19
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 147
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2009b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
const int BL = 147;
const uint16_T B[147] = {
        0,      1,      2,      6,     14,     28,     51,     81,    117,
      153,    182,    196,    185,    148,     87,     12,      0,      0,
        0,      0,      0,     31,     91,    116,     97,     39,      0,
        0,      0,      0,      0,     60,    133,    155,    112,     15,
        0,      0,      0,      0,     14,    153,    239,    228,    113,
        0,      0,      0,      0,      0,    147,    351,    421,    309,
       41,      0,      0,      0,      0,     68,    523,    818,    787,
      374,      0,      0,      0,      0,      0,   1187,   3152,   5062,
     6447,   6953,   6447,   5062,   3152,   1187,      0,      0,      0,
        0,      0,    374,    787,    818,    523,     68,      0,      0,
        0,      0,     41,    309,    421,    351,    147,      0,      0,
        0,      0,      0,    113,    228,    239,    153,     14,      0,
        0,      0,      0,     15,    112,    155,    133,     60,      0,
        0,      0,      0,      0,     39,     97,    116,     91,     31,
        0,      0,      0,      0,      0,     12,     87,    148,    185,
      196,    182,    153,    117,     81,     51,     28,     14,      6,
        2,      1,      0
};

/*coefficients for fir filter with A pass = 1dB, A stop = 120dB, F pass = 9.6 kHz, F stop = 12 kHz and Fs = 96kHz*/
