/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
 *
 * Generated on: 11-Feb-2014 09:38:24
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 74
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2009b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
const int BL = 74;
const uint16_T B[74] = {
        0,      1,     21,     88,    216,    352,    370,    185,      0,
        0,      0,    174,    194,      0,      0,      0,    263,    225,
        0,      0,     25,    477,    230,      0,      0,    291,    843,
       86,      0,      0,   1043,   1576,      0,      0,      0,   6302,
    12897,  12897,   6302,      0,      0,      0,   1576,   1043,      0,
        0,     86,    843,    291,      0,      0,    230,    477,     25,
        0,      0,    225,    263,      0,      0,      0,    194,    174,
        0,      0,      0,    185,    370,    352,    216,     88,     21,
        1,      0
};

/*coefficients for fir filter with A pass = 1dB, A stop = 120dB, F pass = 9.6 kHz, F stop = 12 kHz and Fs = 48kHz*/