/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
 *
 * Generated on: 11-Feb-2014 09:40:27
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 37
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2009b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
//const int BL = 37;
//const uint16_T B[37] = {
        0,      6,      0,     37,      0,    125,      0,    315,      0,
      640,      0,   1091,      0,   1602,      0,   2054,      0,   2322,
    30411,   2322,      0,   2054,      0,   1602,      0,   1091,      0,
      640,      0,    315,      0,    125,      0,     37,      0,      6,
        0
//};


/*coefficients for fir filter with A pass = 1dB, A stop = 120dB, F pass = 9.6 kHz, F stop = 12 kHz and Fs = 24kHz*/